p="/mnt/vms/ss-build/UnrealEngine/Engine/Source/Runtime/DawnRHI/Private/DawnDynamicRHI.cpp"
s=open(p).read()

old=('\tWGPUColorTargetState ColorTarget = {};\n'
     '\tColorTarget.format = DawnTextureFormatFromPixelFormat((EPixelFormat)Initializer.RenderTargetFormats[0]);\n'
     '\tColorTarget.writeMask = WGPUColorWriteMask_All;')

new=(
'\t// Blend state: WITHOUT this ColorTarget.blend stays null -> opaque write, so\n'
'\t// any alpha-blended draw (Slate text emits rgb=white, alpha=glyph-coverage) loses\n'
'\t// its coverage and paints solid white quads. Translate the RHI blend state\n'
'\t// (Initializer.BlendState -> FDawnBlendState) to a WGPUBlendState. Opaque states\n'
'\t// (One/Zero/Add) round-trip to an equivalent no-op blend, so always set it.\n'
'\tauto ToWgpuFactor = [](EBlendFactor F) -> WGPUBlendFactor\n'
'\t{\n'
'\t\tswitch (F)\n'
'\t\t{\n'
'\t\tcase BF_Zero:                      return WGPUBlendFactor_Zero;\n'
'\t\tcase BF_One:                       return WGPUBlendFactor_One;\n'
'\t\tcase BF_SourceColor:               return WGPUBlendFactor_Src;\n'
'\t\tcase BF_InverseSourceColor:        return WGPUBlendFactor_OneMinusSrc;\n'
'\t\tcase BF_SourceAlpha:               return WGPUBlendFactor_SrcAlpha;\n'
'\t\tcase BF_InverseSourceAlpha:        return WGPUBlendFactor_OneMinusSrcAlpha;\n'
'\t\tcase BF_DestAlpha:                 return WGPUBlendFactor_DstAlpha;\n'
'\t\tcase BF_InverseDestAlpha:          return WGPUBlendFactor_OneMinusDstAlpha;\n'
'\t\tcase BF_DestColor:                 return WGPUBlendFactor_Dst;\n'
'\t\tcase BF_InverseDestColor:          return WGPUBlendFactor_OneMinusDst;\n'
'\t\tcase BF_ConstantBlendFactor:       return WGPUBlendFactor_Constant;\n'
'\t\tcase BF_InverseConstantBlendFactor:return WGPUBlendFactor_OneMinusConstant;\n'
'\t\tcase BF_Source1Color:              return WGPUBlendFactor_Src1;\n'
'\t\tcase BF_InverseSource1Color:       return WGPUBlendFactor_OneMinusSrc1;\n'
'\t\tcase BF_Source1Alpha:              return WGPUBlendFactor_Src1Alpha;\n'
'\t\tcase BF_InverseSource1Alpha:       return WGPUBlendFactor_OneMinusSrc1Alpha;\n'
'\t\tdefault:                           return WGPUBlendFactor_One;\n'
'\t\t}\n'
'\t};\n'
'\tauto ToWgpuOp = [](EBlendOperation O) -> WGPUBlendOperation\n'
'\t{\n'
'\t\tswitch (O)\n'
'\t\t{\n'
'\t\tcase BO_Add:             return WGPUBlendOperation_Add;\n'
'\t\tcase BO_Subtract:        return WGPUBlendOperation_Subtract;\n'
'\t\tcase BO_ReverseSubtract: return WGPUBlendOperation_ReverseSubtract;\n'
'\t\tcase BO_Min:             return WGPUBlendOperation_Min;\n'
'\t\tcase BO_Max:             return WGPUBlendOperation_Max;\n'
'\t\tdefault:                 return WGPUBlendOperation_Add;\n'
'\t\t}\n'
'\t};\n'
'\tFBlendStateInitializerRHI::FRenderTarget RT0;\n'
'\tif (FDawnBlendState* BS = static_cast<FDawnBlendState*>(Initializer.BlendState))\n'
'\t{\n'
'\t\tRT0 = BS->Initializer.RenderTargets[0];\n'
'\t}\n'
'\tWGPUBlendState BlendState = {};\n'
'\tBlendState.color.operation = ToWgpuOp(RT0.ColorBlendOp);\n'
'\tBlendState.color.srcFactor = ToWgpuFactor(RT0.ColorSrcBlend);\n'
'\tBlendState.color.dstFactor = ToWgpuFactor(RT0.ColorDestBlend);\n'
'\tBlendState.alpha.operation = ToWgpuOp(RT0.AlphaBlendOp);\n'
'\tBlendState.alpha.srcFactor = ToWgpuFactor(RT0.AlphaSrcBlend);\n'
'\tBlendState.alpha.dstFactor = ToWgpuFactor(RT0.AlphaDestBlend);\n'
'\tWGPUColorWriteMask WriteMask = WGPUColorWriteMask_None;\n'
'\tif (RT0.ColorWriteMask & CW_RED)   { WriteMask |= WGPUColorWriteMask_Red; }\n'
'\tif (RT0.ColorWriteMask & CW_GREEN) { WriteMask |= WGPUColorWriteMask_Green; }\n'
'\tif (RT0.ColorWriteMask & CW_BLUE)  { WriteMask |= WGPUColorWriteMask_Blue; }\n'
'\tif (RT0.ColorWriteMask & CW_ALPHA) { WriteMask |= WGPUColorWriteMask_Alpha; }\n'
'\t{ static uint32 _bd=0; if(_bd++<8) UE_LOG(LogDawnRHI, Warning, TEXT("BLENDDIAG cOp=%d cSrc=%d cDst=%d aSrc=%d aDst=%d mask=%d"), (int)RT0.ColorBlendOp, (int)RT0.ColorSrcBlend, (int)RT0.ColorDestBlend, (int)RT0.AlphaSrcBlend, (int)RT0.AlphaDestBlend, (int)RT0.ColorWriteMask); }\n'
'\n'
'\tWGPUColorTargetState ColorTarget = {};\n'
'\tColorTarget.format = DawnTextureFormatFromPixelFormat((EPixelFormat)Initializer.RenderTargetFormats[0]);\n'
'\tColorTarget.writeMask = WriteMask;\n'
'\tColorTarget.blend = &BlendState;')

assert s.count(old)==1, ("colortarget", s.count(old))
s=s.replace(old,new)
open(p,"w").write(s)
print("blend-state translation applied")
